name: Deploy to CF
description: 'Deploy to CloudFlare'
inputs:
  apiToken:
    description: CloudFlare API key
    required: true
  projectName:
    description: CloudFlare pages project name
    required: true
  accountID:
    description: CloudFlare account id
    required: true
  deployableDir:
    description: Directory with deployable files
    required: false
    default: dist
runs:
  using: 'node20'
  main: 'main.js'