name: Deploy to CF
description: 'Deploy to CloudFlare'
inputs:
  apiToken:
    description: CloudFlare API key
    required: true
  projectName:
    description: CloudFlare pages project name
    required: true
  accountID:
    description: CloudFlare account id
    required: true
  deployableDir:
    description: Directory with deployable files
    required: false
    default: dist
env:
  CLOUDFLARE_ACCOUNT_ID: ${{ inputs.accountID }}
  CLOUDFLARE_API_TOKEN: ${{ inputs.apiToken }}
runs:
  using: 'node16'
  main: 'main.js'