name: Get and cache dependencies
description: Gets dependencies(or reuses from cache, if exists)
outputs:
  cache-hit:
    description: Cache hit output from actions/cache
    value: ${{steps.cache-step.outputs.cache-hit}}
runs:
  using: 'composite'
  steps:
    - name: Cache deps
      id: cache-step
      uses: actions/cache@v4
      with:
        path: node_modules
        key: node_deps_${{ hashFiles('**/package-lock.json') }}
    - name: Get deps
      if: steps.cache-step.outputs.cache-hit != 'true'
      run: npm ci
      shell: bash

